name: 更新Warp2Clash配置

on:
  workflow_dispatch: # 允许手动触发工作流
  schedule:
    - cron: '0 1 * * *' # 每天UTC时间1:00运行

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        
    - name: 运行脚本
      run: |
        chmod +x W2C_start.sh
        if [ ! -e result.csv ]; then
          ./warp >/dev/null 2>&1
        fi
        bash W2C_start.sh iGpo/8+r44JBwD2XndRoUanyf+r0PNdIcEX0Few/jFk= bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo= 2606:4700:110:8215:adc6:2102:b64:dc2/128

        
    - name: 提交更改
      run: |
        git config --global user.email "chenhua.xu@qq.com"
        git config --global user.name "wokaotianshi123"
        git add .
        git commit -m "GitHub Actions自动更新配置文件$(date +'%Y-%m-%d %H:%M:%S')" || echo "没有更改可提交"
        git push
